title: Sreekar Nedunuri # your name (or website title) here
logo: "/images/DP.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Aspiring Software Engineer</b><br>
  <i class="fa fa-home"></i>Charlotte, NC.
  <br><br>
  <p><a href="www.linkedin.com/in/sreekar-nedunuri-9ba74279">View My LinkedIn Profile</a><br>
  Email: sreekarnedunuri@gmail.com</p>
  Reach me at: +1(980)-322-7651</p>
  <span class="fa-stack fa-lg">
  <i class="fa fa-square-o fa-stack-2x"></i>
  <i class="fa fa-twitter fa-stack-1x"></i>
 </span>
  
theme: jekyll-theme-minimal
