title: Sreekar Nedunuri # your name (or website title) here
logo: "/images/DP.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Aspiring Software Engineer</b><br>
  <i class="fa fa-home"></i>Charlotte, NC.
  <br><br>
  <a href="www.linkedin.com/in/sreekar-nedunuri-9ba74279">View My LinkedIn Profile</a> 
  <p>Email: sreekarnedunuri@gmail.com<br>
  Reach me at: +1(980)-322-7651</p>
  
theme: jekyll-theme-minimal
