title: Sreekar Nedunuri # your name (or website title) here
logo: "/images/IMG_20200214_124002__01.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer 
  <br><br>
  <a href="www.linkedin.com/in/sreekar-nedunuri-9ba74279">View My LinkedIn Profile</a>
  <br><br>
  <a href="www.gmail.com">My Email: sreekarnedunuri@gmail.com</a>
  <br><br>
  <b>Reach me at: +1(980)-322-7651</b>
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
