title: Sreekar Nedunuri # your name (or website title) here
logo: "/images/DP.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Aspiring Software Engineer</b><br>
  Charlotte, NC
  <br><br>
  <p><a href="www.linkedin.com/in/sreekar-nedunuri-9ba74279">View My LinkedIn Profile</a><br>
  Email: sreekarnedunuri@gmail.com<br>
  Reach me at: +1(980)-322-7651</p>
  
theme: jekyll-theme-minimal
